In [169]:
import numpy as np
import sympy as sp

In [283]:
class Backpropagation:

    def __init__(self,
                 _no_input_neuron,
                 _hidden_config,
                 _no_output_neuron,
                 _input_data_set,
                 _desired_output,
                 _epoch):
        self.epochs = _epoch

        self.no_of_input_neurons = _no_input_neuron
        self._hidden_config = _hidden_config
        self.no_of_layers = len(_hidden_config)
        self.no_of_hidden_neurons = _hidden_config[0]
        self.no_of_output_neurons = _no_output_neuron

        self.input_data_set = _input_data_set
        self.desired_output = _desired_output
        
        self.eta = 0.03
        
    def generate_weight(self,is_random,_size):
        return np.random.uniform(size=_size) if is_random else np.zeros(_size)
        
    def sigmoid (self,x): 
        return 1/(1 + np.exp(-x)) 
    
    def derivative_(self,x): 
        return x * (1 - x)
    
    def local_field(self,x,w):
        return np.dot(x,w)
    
    def error(self,y):
        return self.desired_output - y
    
    def delta(self,sigma_tic,summed_error,flag = False):
        return summed_error * sigma_tic        
#         return np.dot(sigma_tic,summed_error) if flag else sigma_tic*summed_error

In [338]:
bp = Backpropagation(2,
                     [2],
                     1,
                     np.array([[0,0],[0,1],[1,0],[1,1]]),
                     np.array([[0],[1],[1],[0]]),
                     5000)
Wh = np.random.uniform(size=(bp.no_of_input_neurons, bp._hidden_config[0]))
Wz = np.random.uniform(size=(bp._hidden_config[0],bp.no_of_output_neurons))

for i in range(100000):
    H = bp.sigmoid(np.dot(bp.input_data_set, Wh))                  # hidden layer results
    Z = bp.sigmoid(np.dot(H, Wz))                  # output layer results
    E = bp.desired_output - Z
#     print E
    dZ = E * bp.derivative_(Z) 
    dH = dZ.dot(Wz.T) * bp.derivative_(H)             # delta H
    Wz +=  0.1 * H.T.dot(dZ)                          # update output layer weights
    Wh +=  0.1 * bp.input_data_set.T.dot(dH) 
# print Wh,Wz
print E

[[-0.03263721]
 [ 0.06896294]
 [ 0.06896296]
 [-0.09196158]]


In [313]:
bp = Backpropagation(2,
                     [2],
                     1,
                     np.array([[0,0],[0,1],[1,0],[1,1]]),
                     np.array([[0],[1],[1],[0]]),
                     5000)

current_input = bp.input_data_set
# stacking a column of ones to represent the bias
# current_input = np.column_stack((np.ones((current_input.shape[0],1)),current_input))
# print current_input
all_weights = []
all_inputs = []
all_sigmoids = []
all_inputs.append(current_input)

for i in range(bp.no_of_layers+1):  
    #generating weights for synapsis for hidden layers
    hidden_weights = bp.generate_weight(True,(current_input.shape[1],
                                              bp.no_of_output_neurons if (i == bp.no_of_layers) else bp._hidden_config[i]))
    all_weights.append(hidden_weights)
    
    #computing local field and output of each hidden neuron
    local_field = bp.local_field(current_input,hidden_weights)
    sigmoid = bp.sigmoid(local_field)
    all_sigmoids.append(sigmoid)
    
    current_input = sigmoid
    # stacking a column of ones to represent the bias
#     current_input = np.column_stack((np.ones((sigmoid.shape[0],1)),sigmoid))
    all_inputs.append(current_input)

error = bp.desired_output - all_sigmoids[-1]

all_derivatives = []
print all_inputs
for i in range(bp.no_of_layers+1,0,-1):
    sigmoid_tic_j= bp.derivative_(all_inputs[i])
#     print sigmoid_tic_j
    all_derivatives.append(sigmoid_tic_j)
    
    if i==bp.no_of_layers+1:
        delta_j = bp.delta(sigmoid_tic_j,error)

        delta_w_ji = (bp.eta) * (all_inputs[i].T).dot(delta_j)
        temp_weight = all_weights[i-1]
        all_weights[i-1] = all_weights[i-1].T + delta_w_ji
    else:
        summed_error = delta_j.dot(temp_weight.T)

        delta_j = bp.delta(sigmoid_tic_j,summed_error,True)
        delta_w_ji = (bp.eta) * (all_inputs[i].T).dot(delta_j)
#         print delta_w_ji
#         print delta_j
#         delta_w_ji = ((bp.eta * delta_j) * all_inputs[i-1].T).T

#         temp_weight = all_weights[i-1]
#         all_weights[i-1] = all_weights[i-1].T + delta_w_ji
    
#     sigma_tic =
#     summed_error =
#     delta(self,sigma_tic,summed_error)

[array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]]), array([[ 0.5       ,  0.5       ],
       [ 0.70586895,  0.56045832],
       [ 0.62795598,  0.59158447],
       [ 0.80200326,  0.64874829]]), array([[ 0.71498575],
       [ 0.76423733],
       [ 0.75482003],
       [ 0.79352178]])]


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [192]:
for i in range(6,1):
    print i
print range(3,-1,-1)

[3, 2, 1, 0]


In [ ]:
# output_weights = bp.generate_weight(True,(current_input.shape[1],bp.no_of_output_neurons))
# all_weights.append(output_weights)

# local_field = bp.local_field(current_input,output_weights)
# y_k = bp.sigmoid(local_field)
# all_sigmoids.append(y_k)
# print all_sigmoids

In [132]:
bp = Backpropagation([2,2,1],
                     np.array([[0,0],[0,1],[1,0],[1,1]]),
                     np.array([[0],[1],[1],[0]]),
                     5000)
hidden_weights = bp.generate_weight(True,(bp.no_of_input_neurons,bp.no_of_hidden_neurons+1))
output_weights = bp.generate_weight(True,(1,bp.no_of_hidden_neurons,bp.no_of_output_neurons+1))

print hidden_weights
h_localfield = bp.local_field(bp.input_data_set,hidden_weights)
y_j = bp.sigmoid(h_localfield)

o_local_field = bp.local_field(y_j,output_weights)
y_k = bp.sigmoid(o_local_field)
e = bp.error(y_k)
print e

[[ 0.89447008  0.09125759  0.67917874]
 [ 0.07006443  0.47297002  0.48245074]]


ValueError: shapes (4,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)