In [1]:
import numpy as np

num_visible = 2
num_hidden = 3
_eta = 0.1

def logistic(v):
    return 1.0/(1 + np.exp(-v))

def training(training_data,weights,bias):
    new_input = []
    for input_ in training_data:
        x1 = input_[0]
        x2 = input_[1]
    
        a = []
        for i in range(num_hidden):
            w1 = weights.T[i]
            res = ((x1*w1[0]) + (x2*w1[1])) + bias[i]
            activation_val = logistic(res)
            a.append(activation_val)
        new_input.append(a)
    new_input = np.asarray(new_input)
    return new_input

def reconstruction(new_input,weights,bias):
    
    list_ = []
    for input_ in new_input:
        h1 = input_[0]
        h2 = input_[1]
        h3 = input_[2]
        a = []
        for i in range(num_visible):
            w1 = weights.T
            wt = w1[:,i]
            res = ((h1*wt[0]) + (h2*wt[1]) + (h3*wt[2])) + bias[i]
            activation_val = logistic(res)
            a.append(activation_val)
        list_.append(a)
    list_ = np.asarray(list_)
    return list_


In [2]:
training_data = np.array([[0,1],[1,0]])
weights = np.random.rand(num_visible, num_hidden)
h_bias = np.random.rand(num_hidden)
v_bias = np.random.rand(num_visible)
new_input = training(training_data,weights,h_bias)

reconstructed_input = reconstruction(new_input,weights,v_bias)
print "Initial Training data: \n",training_data
print "\nInitial Weight : \n",weights
print "\nFirst Reconstructed Input:  \n",reconstructed_input

delta_w = _eta*(training_data - reconstructed_input)

print "\nDelta_w : \n",delta_w

for i in range(training_data.shape[0]):
    print "\nAdjusted weights for input ",list(reconstructed_input[i])
    weights[0] = weights[0] + delta_w[i][0]
    weights[1] = weights[1] + delta_w[i][1]
    print "\n",weights

Initial Training data: 
[[0 1]
 [1 0]]

Initial Weight : 
[[ 0.07088979  0.50164408  0.23336418]
 [ 0.8282879   0.26804424  0.94415865]]

First Reconstructed Input:  
[[ 0.75407081  0.858215  ]
 [ 0.75123779  0.83066208]]

Delta_w : 
[[-0.07540708  0.0141785 ]
 [ 0.02487622 -0.08306621]]

Adjusted weights for input  [0.75407081049310576, 0.85821500140212958]

[[-0.00451729  0.426237    0.1579571 ]
 [ 0.8424664   0.28222274  0.95833715]]

Adjusted weights for input  [0.75123778913491357, 0.83066207634674205]

[[ 0.02035893  0.45111322  0.18283332]
 [ 0.75940019  0.19915654  0.87527094]]
