In [1]:
import numpy as np

num_visible = 2
num_hidden = 3
_eta = 0.1

def logistic(v):
    return 1.0/(1 + np.exp(-v))

def training(training_data,weights,bias):
    new_input = []
    for input_ in training_data:
        x1 = input_[0]
        x2 = input_[1]
    
        a = []
        for i in range(num_hidden):
            w1 = weights.T[i]
            res = ((x1*w1[0]) + (x2*w1[1])) + bias[i]
            activation_val = logistic(res)
            a.append(activation_val)
        new_input.append(a)
    new_input = np.asarray(new_input)
    return new_input

def reconstruction(new_input,weights,bias):
    
    list_ = []
    for input_ in new_input:
        h1 = input_[0]
        h2 = input_[1]
        h3 = input_[2]
        a = []
        for i in range(num_visible):
            w1 = weights.T
            wt = w1[:,i]
            res = ((h1*wt[0]) + (h2*wt[1]) + (h1*wt[2])) + bias[i]
            activation_val = logistic(res)
            a.append(activation_val)
        list_.append(a)
    list_ = np.asarray(list_)
    return list_


In [2]:
training_data = np.array([[0,1],[1,0]])
weights = np.random.rand(num_visible, num_hidden)
h_bias = np.random.rand(num_hidden)
v_bias = np.random.rand(num_visible)
new_input = training(training_data,weights,h_bias)

reconstructed_input = reconstruction(new_input,weights,v_bias)
print "Initial Training data:",training_data
print
print "First Reconstructed Input:",reconstructed_input
print

delta_w = _eta*(training_data - reconstructed_input)

print "Initial Weight :",weights
print

print "Delta_w :",delta_w
print

for i in range(training_data.shape[0]):
    print "Adjusted weights for input : ",list(reconstructed_input[i])
    weights[0] = weights[0] + delta_w[i][0]
    weights[1] = weights[1] + delta_w[i][1]
    print weights
    print

Initial Training data: [[0 1]
 [1 0]]

First Reconstructed Input: [[ 0.80302224  0.80238122]
 [ 0.79319218  0.79580306]]

Initial Weight : [[ 0.33524447  0.27492961  0.70691733]
 [ 0.57625072  0.40355542  0.0174213 ]]

Delta_w : [[-0.08030222  0.01976188]
 [ 0.02068078 -0.07958031]]

Adjusted weights for input :  [0.80302224353206264, 0.8023812175465459]
[[ 0.25494224  0.19462738  0.62661511]
 [ 0.5960126   0.42331729  0.03718318]]

Adjusted weights for input :  [0.79319218234274147, 0.79580306237274812]
[[ 0.27562302  0.21530817  0.64729589]
 [ 0.51643229  0.34373699 -0.04239713]]

